#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const destination = path.join(root, 'compat', 'codex-0.154', 'agentguard');
const copiedDirectories = ['runtime', 'hooks', 'config', 'skills', 'assets', 'docs'];
const copiedFiles = ['.app.json', 'LICENSE', 'README.md', 'CHANGELOG.md', 'scripts/provision-dependencies.cjs', 'scripts/print-trust-state.cjs'];
const jsonBytes = value => Buffer.from(JSON.stringify(value, null, 2) + '\n');

function codexHooks() {
  const source = JSON.parse(fs.readFileSync(path.join(root, 'hooks/hooks.json'), 'utf8'));
  delete source.hooks.PostToolUseFailure;
  for (const groups of Object.values(source.hooks)) for (const group of groups) {
    for (const hook of group.hooks) hook.command = hook.command.replaceAll('${CLAUDE_PLUGIN_ROOT}', '${PLUGIN_ROOT}');
  }
  return jsonBytes(source);
}

function collect(directory, prefix = '') {
  return fs.readdirSync(directory, {withFileTypes: true}).flatMap(entry => {
    if (entry.name === 'node_modules') return [];
    const relative = path.join(prefix, entry.name);
    if (entry.isDirectory()) return collect(path.join(directory, entry.name), relative);
    if (!entry.isFile()) throw new Error(`Unexpected non-file compatibility source: ${relative}`);
    return [relative];
  });
}

function expectedFiles() {
  const expected = new Map();
  for (const name of copiedFiles) expected.set(name, fs.readFileSync(path.join(root, name)));
  for (const directory of copiedDirectories) {
    for (const name of collect(path.join(root, directory), directory)) expected.set(name, fs.readFileSync(path.join(root, name)));
  }
  // Preserve the installed Codex hook source path and its trust identities.
  // Claude's additional failure event is outside this released Codex schema.
  expected.set('hooks/hooks.json', codexHooks());
  expected.set('hooks/codex-hooks.json', codexHooks());
  // Keep the portable hooks' explicit allow envelope. This release accepts
  // an empty response for allow unless the hook also supplies updatedInput.
  for (const [name, gate] of [['spend-gate', 'spend'], ['burn-gate', 'burn']]) {
    expected.set(`hooks/${name}.cjs`, Buffer.from(`#!/usr/bin/env node\n'use strict';\nrequire('../runtime/client.cjs').run('${gate}', {legacyAllow: true});\n`));
  }
  const portable = JSON.parse(fs.readFileSync(path.join(root, 'plugin.json'), 'utf8'));
  const extension = portable.extensions['com.openai'];
  const legacy = {
    name: portable.name, version: portable.version, description: portable.description,
    author: portable.author, homepage: portable.homepage, repository: portable.repository,
    license: portable.license, keywords: portable.keywords,
    skills: './skills/', mcpServers: './.mcp.json', apps: extension.apps,
    hooks: './hooks/hooks.json', interface: extension.interface,
  };
  expected.set('.codex-plugin/plugin.json', jsonBytes(legacy));
  const portableMcp = JSON.parse(fs.readFileSync(path.join(root, 'mcp.json'), 'utf8'));
  const mcpServers = Object.fromEntries(Object.entries(portableMcp.mcpServers).map(([name, config]) => {
    if (config.type !== 'stdio') throw new Error('Compatibility packaging currently supports local stdio MCP only');
    if (name !== 'agentguard') throw new Error('Unknown compatibility MCP server');
    return [name, {command: config.command, args: ['runtime/mcp-legacy.cjs'], cwd: '.'}];
  }));
  expected.set('.mcp.json', jsonBytes({mcpServers}));
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  pkg.scripts = {start: 'node runtime/mcp.cjs', postinstall: 'node scripts/provision-dependencies.cjs'};
  pkg.files = ['.codex-plugin', '.mcp.json', '.app.json', ...copiedDirectories, 'scripts/provision-dependencies.cjs', 'scripts/print-trust-state.cjs', 'README.md', 'LICENSE', 'CHANGELOG.md'];
  expected.set('package.json', jsonBytes(pkg));
  const lock = JSON.parse(fs.readFileSync(path.join(root, 'package-lock.json'), 'utf8'));
  expected.set('package-lock.json', jsonBytes(lock));
  expected.set('COMPATIBILITY.md', Buffer.from('# Codex 0.154 compatibility installation\n\nGenerated by `node scripts/build-compat.cjs` from the canonical plugin.\nDo not edit these copies; edit the package root and regenerate them.\n\nCodex 0.154.0 skips hook loading for portable Agent Plugins manifests.\nThis installation uses its supported legacy manifest while preserving the\ncanonical package\'s hook code, skills, assets, registry dependencies, and policy.\nThe portable root plugin.json deliberately does not appear in this directory.\n\nSource: https://github.com/openai/codex/blob/rust-v0.154.0/codex-rs/core-plugins/src/loader.rs#L954\n'));
  return expected;
}

function check() {
  if (!fs.readFileSync(path.join(root, 'hooks/codex-hooks.json')).equals(codexHooks())) throw new Error('Codex hook adapter is stale; run npm run build:compat.');
  const expected = expectedFiles();
  const missingOrChanged = [...expected].filter(([name, bytes]) => {
    try { return !fs.readFileSync(path.join(destination, name)).equals(bytes); } catch { return true; }
  }).map(([name]) => name);
  const extras = fs.existsSync(destination) ? collect(destination).filter(name => !expected.has(name)) : [];
  if (missingOrChanged.length || extras.length) {
    throw new Error(`Compatibility artifact is stale; run npm run build:compat. Changed: ${missingOrChanged.join(', ')}. Unexpected: ${extras.join(', ')}`);
  }
  return expected.size;
}

function build() {
  fs.writeFileSync(path.join(root, 'hooks/codex-hooks.json'), codexHooks());
  const expected = expectedFiles();
  for (const [name, bytes] of expected) {
    const target = path.join(destination, name);
    fs.mkdirSync(path.dirname(target), {recursive: true});
    fs.writeFileSync(target, bytes);
  }
  return check();
}

module.exports = {build, check, expectedFiles, destination, codexHooks};
if (require.main === module) {
  try {
    const count = process.argv.includes('--check') ? check() : build();
    process.stdout.write(`Codex compatibility artifact: ${count} files ${process.argv.includes('--check') ? 'verified' : 'generated'}\n`);
  } catch (error) {process.stderr.write(error.message + '\n');process.exitCode = 1;}
}
